schema_version: 1

context:
  version: "1.5.1"
  python_min: "3.11"

package:
  name: serena-agent
  version: ${{ version }}

source:
  url: https://github.com/oraios/serena/archive/v${{ version }}.tar.gz
  sha256: b5a7c41734fc5f53bab76f69fb7d10ce282fe772caec4c340d8c0d358f4f8e88
  patches:
    - relax-deps.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - serena = serena.cli:top_level
      - serena-hooks = serena.hooks:hook_commands
requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - requests >=2.33.0
    - pyright >=1.1.403
    - overrides >=7.7.0
    - python-dotenv >=1.2.2
    - mcp ==1.27.0
    - flask >=3.1.3
    - sensai-utils >=1.5.0
    - pydantic >=2.12.5
    - types-pyyaml >=6.0.12.20250516
    - pyyaml >=6.0.2
    - ruamel.yaml >=0.18.14
    - jinja2 >=3.1.6
    - pathspec >=0.12.1
    - psutil >=7.0.0
    - docstring_parser >=0.17.0
    - joblib >=1.5.1
    - tqdm >=4.67.1
    - tiktoken >=0.12.0
    - anthropic >=0.59.0
    - beautifulsoup4 >=4.14.2


tests:
  - python:
      imports:
        - serena
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - serena --help
      - serena-hooks --help

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/oraios/serena
  summary: Serena is a powerful coding agent toolkit capable of turning an LLM into a fully-featured agent that works directly on your codebase. Unlike most other tools, it is not tied to an LLM, framework or an interface, making it easy to use it in a variety of ways.

extra:
  recipe-maintainers:
    - swenger
